---
name: "Jellyfin Ignore"
guid: "277cd84e-44c3-45a1-8f3c-2537ddac0ccf"
version: "0.5.0.0"
targetAbi: "10.9.0.0"
framework: "net8.0"
overview: "Specifiy filepath patterns to ignore on library scan"
description: >
  This Jellyfin plugin allows you to specify filepath patterns to ignore when performing a library scan. It can for example ignore specific file extensions (like .m3u). The patterns can be specified on the plugin configuration page.
category: "General"
owner: "fdett"
artifacts:
- "Jellyfin.Plugin.Ignore.dll"
changelog: >
  Update for 10.9 + dotnet8.0 and bugfix when null parent folder
imageUrl: "https://raw.githubusercontent.com/fdett/jellyfin-ignore/master/img/image.png"
